name: localizations_date
description: Localization flutter - Date
version: 1.2.1
homepage: https://sudo.dog

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
